"""Chunk contextualisation for RAG ingestion.

Implements the Anthropic contextual retrieval pattern:
https://www.anthropic.com/news/contextual-retrieval

Before embedding, each chunk is enriched with a short document-level
context sentence generated by the org's configured LLM. This makes
the stored vectors richer and improves recall for all downstream steps
(hybrid search, reranking, routing).

The function is called once per document during ingestion (not at
query time) so there is no latency impact on live voice calls.
"""

from __future__ import annotations

import asyncio
from typing import Optional

from loguru import logger

# Maximum characters of the document to include in the contextualisation
# prompt.  We pass the first N chars so the LLM understands the doc's
# overall topic without hitting token limits.
_DOC_CONTEXT_CHARS = 2000

# Number of chunks to contextualise in parallel per document.
_CONTEXTUALISE_CONCURRENCY = 10

# System prompt used for contextualisation
_SYSTEM_PROMPT = (
    "You are a precise document analyst for an equipment/product catalog. "
    "Your job is to add a single short sentence of context to a document chunk "
    "so it can be retrieved more accurately by a search system. "
    "CRITICAL: Always include the specific product/model name and manufacturer "
    "in your context sentence. Without the model name, the chunk becomes "
    "unsearchable. "
    "Return ONLY the enriched chunk text — do not add any preamble, "
    "explanation, or markdown."
)

_USER_PROMPT_TEMPLATE = """\
Here is the beginning of the document for context:
<document_start>
{doc_start}
</document_start>

Here is the chunk that needs contextualisation:
<chunk>
{chunk_text}
</chunk>

{parent_entity_hint}
Prepend a single short sentence (max 30 words) that includes the specific \
product/model name and manufacturer, and describes what information this \
chunk contains. Then reproduce the original chunk text unchanged.
Return only the result — no labels, no markdown."""


async def contextualise_chunks(
    chunks: list[dict],
    filename: str,
    llm_provider: Optional[str] = None,
    llm_api_key: Optional[str] = None,
    llm_model: Optional[str] = None,
    llm_base_url: Optional[str] = None,
    parent_entities: Optional[dict[int, str]] = None,
) -> list[dict]:
    """Enrich chunk contextualized_text with a document-level summary sentence.

    Runs concurrently across all chunks for a document.  Falls back
    gracefully — if the LLM call fails for a chunk the original
    contextualized_text is kept unchanged.

    Args:
        chunks: List of chunk dicts as returned by MPS.  Each must have
            ``chunk_text`` and ``chunk_index`` keys.
        filename: Original document filename (used as a hint in the prompt).
        llm_provider: Provider name (e.g. "openai", "dograh").
        llm_api_key: API key for the LLM.
        llm_model: Model ID to use (e.g. "gpt-4o-mini").
        llm_base_url: Optional base URL override.
        parent_entities: Optional mapping of chunk_index → parent entity name
            (e.g. "Kobelco CKE1350-1F"). Used to ensure orphaned chunks
            still reference their parent model in the contextualised text.

    Returns:
        The same list of chunks with ``contextualized_text`` updated where
        contextualisation succeeded.
    """
    if not llm_api_key or not chunks:
        logger.debug(
            "Skipping chunk contextualisation — no LLM API key or no chunks"
        )
        return chunks

    # Build the document start from the first chunks' text
    doc_start = _build_doc_start(chunks, filename)

    # If no parent_entities map provided, try to build one from chunk text
    # by scanning for model names in each chunk and propagating to subsequent ones
    if parent_entities is None:
        parent_entities = _infer_parent_entities(chunks)

    semaphore = asyncio.Semaphore(_CONTEXTUALISE_CONCURRENCY)

    async def _contextualise_one(chunk: dict) -> dict:
        """Contextualise a single chunk, falling back on any error."""
        chunk_text = chunk.get("chunk_text") or ""
        if not chunk_text.strip():
            return chunk

        chunk_idx = chunk.get("chunk_index", 0)
        entity_hint = ""
        if parent_entities and chunk_idx in parent_entities:
            entity_name = parent_entities[chunk_idx]
            entity_hint = (
                f"IMPORTANT: This chunk belongs to the product/model: {entity_name}. "
                f"You MUST include \"{entity_name}\" in your context sentence."
            )

        async with semaphore:
            try:
                enriched = await _call_llm(
                    chunk_text=chunk_text,
                    doc_start=doc_start,
                    parent_entity_hint=entity_hint,
                    llm_provider=llm_provider,
                    llm_api_key=llm_api_key,
                    llm_model=llm_model,
                    llm_base_url=llm_base_url,
                )
                # Return a shallow copy so we don't mutate the original in-place
                return {**chunk, "contextualized_text": enriched}
            except Exception as exc:
                logger.warning(
                    "Chunk contextualisation failed for chunk {} of '{}': {}",
                    chunk.get("chunk_index"),
                    filename,
                    exc,
                )
                return chunk

    results = await asyncio.gather(*[_contextualise_one(c) for c in chunks])
    logger.info(
        "Contextualised {}/{} chunks for '{}'",
        sum(
            1
            for orig, enriched in zip(chunks, results)
            if enriched.get("contextualized_text") != orig.get("contextualized_text")
        ),
        len(chunks),
        filename,
    )
    return list(results)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_doc_start(chunks: list[dict], filename: str) -> str:
    """Concatenate the first N characters of the document from early chunks."""
    parts = [f"Document: {filename}\n"]
    char_count = len(parts[0])
    for chunk in sorted(chunks, key=lambda c: c.get("chunk_index", 0)):
        text = chunk.get("chunk_text") or ""
        if char_count + len(text) > _DOC_CONTEXT_CHARS:
            remaining = _DOC_CONTEXT_CHARS - char_count
            if remaining > 0:
                parts.append(text[:remaining])
            break
        parts.append(text)
        char_count += len(text)
    return " ".join(parts)


def _infer_parent_entities(chunks: list[dict]) -> dict[int, str]:
    """Infer parent entity (model/product name) for each chunk by scanning text.

    Strategy: scan chunks in order. When a chunk contains a recognizable entity
    pattern (e.g. model name in JSON like "model" : "Kobelco CKE1350-1F"),
    assign it as the current entity. Propagate that entity to subsequent chunks
    until a new entity is found.

    This handles the common case where a JSON record is split across multiple
    chunks — only the first chunk has the model name, but all subsequent chunks
    (specs, sections) belong to the same model.
    """
    import re

    # Pattern to find model names in JSON-chunked text:
    # " model " : " kobelco cke1350 - 1f "
    # Or cleaner: "model": "Kobelco CKE1350-1F"
    model_pattern = re.compile(
        r'(?:"model"\s*:\s*"([^"]+)")|'        # clean JSON
        r'(?:model\s*"\s*:\s*"\s*([^"]+?)(?:\s*"))',  # spaced JSON from MPS
        re.IGNORECASE,
    )

    # Also try to find "id" fields that often carry the model identifier
    id_pattern = re.compile(
        r'(?:"id"\s*:\s*"([^"]+)")|'
        r'(?:id\s*"\s*:\s*"\s*([^"]+?)(?:\s*"))',
        re.IGNORECASE,
    )

    entities: dict[int, str] = {}
    current_entity: str | None = None

    sorted_chunks = sorted(chunks, key=lambda c: c.get("chunk_index", 0))

    for chunk in sorted_chunks:
        chunk_idx = chunk.get("chunk_index", 0)
        text = chunk.get("chunk_text") or ""

        # Try to find a model name in this chunk
        match = model_pattern.search(text)
        if match:
            found = (match.group(1) or match.group(2) or "").strip()
            if found and len(found) >= 3:
                # Normalize: collapse "kobelco cke1350 - 1f" → "Kobelco CKE1350-1F"
                # by title-casing and removing extra spaces around hyphens
                normalized = re.sub(r'\s*-\s*', '-', found)
                normalized = re.sub(r'\s+', ' ', normalized).strip()
                current_entity = normalized

        # Assign current entity to this chunk
        if current_entity:
            entities[chunk_idx] = current_entity

    logger.debug(
        "Inferred parent entities for {}/{} chunks ({} unique entities)",
        len(entities),
        len(chunks),
        len(set(entities.values())),
    )
    return entities


async def _call_llm(
    *,
    chunk_text: str,
    doc_start: str,
    parent_entity_hint: str = "",
    llm_provider: Optional[str],
    llm_api_key: str,
    llm_model: Optional[str],
    llm_base_url: Optional[str],
) -> str:
    """Call the org's LLM to generate contextualised text for one chunk."""
    from openai import AsyncOpenAI

    model = llm_model or "gpt-4o-mini"
    client_kwargs: dict = {"api_key": llm_api_key}

    effective_base_url = llm_base_url
    if not effective_base_url and llm_provider:
        _provider_lower = str(llm_provider).lower()
        if "dograh" in _provider_lower:
            from api.constants import MPS_API_URL
            effective_base_url = f"{MPS_API_URL}/api/v1/llm"
            model = llm_model or "default"

    if effective_base_url:
        client_kwargs["base_url"] = effective_base_url

    client = AsyncOpenAI(**client_kwargs)

    user_prompt = _USER_PROMPT_TEMPLATE.format(
        doc_start=doc_start,
        chunk_text=chunk_text,
        parent_entity_hint=parent_entity_hint,
    )

    response = await client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.0,
        max_tokens=512,
    )

    enriched = response.choices[0].message.content or chunk_text
    return enriched.strip()
